### PR TITLE
Issue #70 - Added NuSpec file for NSwag Console.

### PR DESCRIPTION
**Pull request by jkonecki**
The new package can be easily referenced in a project and a simple PostBuild task can be added as required.

### CODE REVIEW

**Comment by rsuter** [comment]
Thanks for PR, I have to check the generated nuget.. I think it has dependencies to all other packages even if everything is included in the package... If it is like that we have to fix this first..

**Comment by jkonecki** [comment]
Sure. I haven't defined any dependencies so it should be a stand-alone package. Let me know if otherwise.

**Comment by rsuter** [comment]
... the nuspec has not been not picked up. You have to rename it to `NSwag.nuspec` (same as project file) so that the build agent finds the nuspec...

**Comment by rsuter** [comment]
.. and please add an empty `<dependencies></dependencies>` tag - maybe this forces the packager to omit all dependencies..

**Comment by rsuter** [comment]
Usually the NuGet packager automatically determines all referenced projects in the csproj file and adds them to the dependency list...

**Comment by rsuter** [comment]
How do you reference the nuget dlls in the postbuild and where do you install this nuget? I think you have to hardcode the full path (ie. full nuget name + version) into the csproj/msbuild task

**Comment by jkonecki** [comment]
Yes, that's correct. Similar is needed for example for NUnit.ConsoleRunner.
What should be the Id for the console package? After I change the name to NSwag.nuspec the package name will be called NSwag.nuget. I think NSwag.Console.nuget is a better name for the package.

**Comment by rsuter** [comment]
the id will be copied from the AssemblyInfo.cs which is NSwag.Console...

**Comment by jkonecki** [comment]
Ah, yes. You're using $id$. Making the change now

**Comment by rsuter** [comment]
I think it would be much better, if we create a `NSwag.MSBuild` package with a .targets file which is automatically added to the project and which provides nice build tasks and always uses the installed package...

**Comment by rsuter** [comment]
Now its the wrong id :-): https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/195/artifacts
we have to hard code it in the nuspec

**Comment by rsuter** [comment]
And the dependencies are added: 

image

**Comment by jkonecki** [comment]
How are you building the packages? I couldn't find anything in code.
Are you passing -IncludedReferencedProjects?
I think there's an option to prefer nuspec file over csproj

**Comment by rsuter** [comment]
Its built by AppVeyor with IncludeReferencedProjects (required for other nuspecs)... I have to check how to do this - and if possible do the .targets solution because it is much simpler to use..

**Comment by jkonecki** [comment]
Targets file is a nice idea - my only issue is that I would like to avoid having to install all NSwag packages in my project with the references added as I don't want to deploy NSwag.*.dlls with the application.

**Comment by rsuter** [comment]
It will be a development dependency and no dlls are referenced, just the targets file, but this file will no be published..

**Comment by jkonecki** [comment]
At the moment I'm integrating NSwag into my project and having a package with exe inside is sufficient for me. I'm happy to help you with the targets file in the near future.

**Comment by rsuter** [comment]
Ok, it will be one of my next tasks..

**Comment by rsuter** [comment]
See here: https://github.com/NSwag/NSwag/wiki/MSBuild

**Comment by rsuter** [comment]
Is this the way you expect this to be?

**Comment by rsuter** [comment]
Use NSwag.MSBuild package instead

**Comment by jkonecki** [comment]
The `NSwag.MSBuild` package works perfectly fine. Thank you very much!

I however have a problem with the following command:

`nswag,exe webapi2swagger /assembly:MyWebApi.dll /output:swagger.json`
Please note that I don't provide `/controller` argument. 

Instead of processing all the controllers the app shows the message: _The Web API controller full class name or empty to load all controllers from the assembly._ followed by _Controller:_ and prompt. 
According to the wiki omitting the `/controller` argument should be enough to process all controllers. What am I doing wrong?

**Comment by jkonecki** [comment]
I've noticed that if I press <Enter> in the console there will be an exception in 

```
        public AppDomainIsolation(string assemblyDirectory, string assemblyConfiguration)
        {
            if (string.IsNullOrEmpty(assemblyDirectory))
                throw new ArgumentNullException(nameof(assemblyDirectory));
```

as the `assembyDirectory` is an empty string. It is returned from `Path.GetDirectoryName(Settings.AssemblyPath)`

Did you mean `Path.GetFullPath(Settings.AssemblyPath)`?

**Comment by rsuter** [comment]
You are probably right, if assembly path is relative it may be a problem... I also have to check the cmd line param defaults..

**Comment by rsuter** [comment]
Ok both problems should be fixed in: https://github.com/NSwag/NSwag/commit/73159d287f4704e88296eac33f3b5a4e1d543187

Can you download the cmd line tools from the build artifacts and replace your files to test it:
https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/214

If everything is fine, I'll release a new nuget...

**Comment by jkonecki** [comment]
Works fine, thank you!
I'm getting `The operation has more than one body parameter` exception but this is related to my schema I believe. You can publish the packages.

**Comment by rsuter** [comment]
v2.33 should be live in 15 minutes... please inform me if NSwag.MSBuild upgrade works flawlessly (ie new targets file is referenced in project file, ...)

**Comment by jkonecki** [comment]
Upgrade was fine, project file was updated correctly. Thanks again!

**Comment by rsuter** [comment]
Ok, fine.. Please create new issues if you encounter more problems... I mainly use the UI..

**Comment by jkonecki** [comment]
I will. I think you can close the related issue #70.

**Pull request closed without merging**
