### PR TITLE
Correctly serialize readonly properties

### PR DESCRIPTION
**Pull request by LordJZ**
* Json Schema does not specify "readonly" on definition properties
* Swagger specifies it as "readOnly"
* Newtonsoft.Json and NJsonSchema serialize IsReadOnly as "readonly"
* Fix it by remapping "readonly" to "readOnly"

### CODE REVIEW

**Comment by rsuter** [comment]
Maybe we should fix this in NJsonSchema?

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/80ee9989c77839b3e8312f894320eff911adb8d7

**Comment by rsuter** [comment]
http://json-schema.org/latest/json-schema-hypermedia.html#rfc.section.4.4

**Comment by LordJZ** [comment]
@rsuter then we should fix it in Newtonsoft.Json too?

**Comment by LordJZ** [comment]
https://github.com/JamesNK/Newtonsoft.Json/pull/1280
Thanks!

**Comment by rsuter** [comment]
Yes, but im not the maintainer of this repo... :-)

**Comment by rsuter** [comment]
Ok we could revert your pr as soon as njs is updated...

**Pull request merged**
