### PR TITLE
Adds support for custom HttpParameterBinders and Type Mapped primitives.

### PR DESCRIPTION
**Pull request by Cephei**
#621 #634

### CODE REVIEW

**Comment by Cephei** [comment]
Not sure why the integration tests are failing here. @rsuter can you please assist when you have time. Thanks!

**Comment by grovesNL** [comment]
@Cephei I think your build should be ok. They're just compilation errors from TypeScript that I'm working on fixing in https://github.com/NSwag/NSwag/pull/632

**Comment by rsuter** [comment]
Looks good, thanks. But is there really no way to instantiate this factory and read the property? I'd like to avoid adding a new NSwag attribute...

**Comment by Cephei** [comment]
I so wish that was possible. I hated this being the solution. Here's an example to help illustrate why it's not:

```
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Parameter)]
    public sealed class DocumentCreationSourceAttribute : ParameterBindingAttribute
    {
        public override HttpParameterBinding GetBinding(HttpParameterDescriptor parameter)
        {
            if (parameter == null)
            {
                throw new Exception("parameter");
            }

            if (parameter.Configuration.DependencyResolver == null)
            {
                return null;
            }

            return new DocumentCreationSourceParameterBinding(
                parameter, 
                parameter.Configuration.DependencyResolver.GetService(typeof(IDocumentCreationSourceProvider)) as IDocumentCreationSourceProvider);
        }
    }
```

The actual parameter binder:
```
    public class DocumentCreationSourceParameterBinding : HttpParameterBinding
    {
        private static readonly Task<Object> _CompletedTaskReturningNull = Task.FromResult<Object>(null);

        private readonly IDocumentCreationSourceProvider _Provider;

        public DocumentCreationSourceParameterBinding(
            HttpParameterDescriptor parameter,
            IDocumentCreationSourceProvider provider) : base(parameter)
        {
            _Provider = provider;
        }

        public override Task ExecuteBindingAsync(
            ModelMetadataProvider metadataProvider,
            HttpActionContext actionContext,
            CancellationToken cancellationToken)
        {
            var source = actionContext.Request
                .GetQueryNameValuePairs()
                .MaybeSingle(kvp => kvp.Key.Equals("source", StringComparison.OrdinalIgnoreCase) && !String.IsNullOrWhiteSpace(kvp.Value))
                .Bind(kvp => _Provider.Find(kvp.Value).ToMaybe())
                .FromMaybe(null);

            actionContext.ActionArguments[Descriptor.ParameterName] = source;

            return _CompletedTaskReturningNull;
        }
    }
```

**Comment by Cephei** [comment]
Also, I made it so they don't have to use the NSwag.Attributes.WillReadBodyAttribute. They can use their own WillReadBodyAttribute as long as it follows convention.

**Comment by rsuter** [comment]
Why do we need a WillReadBody property on the attribute? I think the attribute alone should be alone to mark a parameter/attribute that it reads the body (like [Required]). Or at least the default should be "true"

**Comment by rsuter** [comment]
2. Why do you disable this for Asp.NET Core? Doesn't it make sense there?

**Comment by Cephei** [comment]
*WillReadBody Property*
I considered this as well, and the original intentions was to support .net core ... before learning more about Core. So Owin/WebAPI differs from Core. Complex types in WebAPI are assumed to read from the body. Whereas complex types in Core are bound from the URI (reflectively looking at properties).

If I don't expose this property, WebAPI would automatically think my `DocumentCreationSourceAttribute` will read from the body. Without this property, I would need to have a [NonBody] attribute. I didn't like that.

*Asp.net Core*
I'm very new to .net core but tried to do as much research on this as I could. In Core, there is no more ParameterBindingAttribute or HttpParameterBinder. Core uses ModelView binding which you're going to have an even larger challenge supporting. Aside from the attributes you already support (e.g. FromUri, FromBody, FromRoute, FromHeader) you can implement your own IModelBinder / IModelBinderProvider and add them to your `MvcOptions`. (see https://www.stevejgordon.co.uk/html-encode-string-aspnet-core-model-binding)

These model binders are centralized much how Owin/WebAPI actually supports centralized parameter bindings (which will be a problem for me soon). Swashbuckle leverages your `HttpConfiguration` to create OpenAPI documentation. The `HttpConfiguration` instance providers you all your route information and access to centralized model binders. I originally loved that NSwag didn't require `HttpConfiguration` and just ApiController Type's or assemblies, however, that comes at a cost. Something to consider going forward ... parameter/model binding does not require attributes. They can be part of the core model binder collection that can't be discovered using reflection.

**Comment by Cephei** [comment]
Example of centralized model binding in WebAPI / OWIN:

```
// NOTE HERE
// configuration is an instance of HttpConfiguration

// --------------------------------------------- ModelBinders --------------------------------------
            var bindingRules = configuration.ParameterBindingRules;
            bindingRules.Add(param =>
            {
                if (!param.ParameterType.IsGenericType) return null;
                if (!typeof(PatchRequestBase).IsAssignableFrom(param.ParameterType)) return null;

                return param.BindWithAttribute(new PatchRequestParameterBindingAttribute());
            });

            bindingRules.Add(
                param =>
                {
                    if (!(typeof(QueryOptions).IsAssignableFrom(param.ParameterType)))
                    {
                        return null;
                    } 

                    return param.BindWithAttribute(new QueryOptionsParameterBindingAttribute());
                });
```

**Comment by rsuter** [comment]
**WillReadBody Property**

Ok, then its fine. Can we at least have the default "true"?

**ASP.NET Core**

Maybe we should also use ApiExplorer for ASP.NET Core and ASP.NET... I think there shouldn't be a downside to that except more dependencies... Or is this a bad idea except that it will be time consuming? Is Swashbuckle working better out of the box or with extenisons?

**Comment by Cephei** [comment]
We can default it to true. I was torn on that but since HttpParameterBinding.WillReadBody defaults to false, I went with that.

**Comment by Cephei** [comment]
Better support for .NET Core / WebAPI would require a bit of a redesign around NSwag, and more dependencies like you stated, but I do think it would be worth it. One of the reasons I loved NSwag was that I have multiple HttpConfiguration's within an Owin pipeline:

/v{apiVersion}/ -> main AppBuilder for the entire API
/scim/v{apiVersion}/ -> SCIM routes from Owin.Scim (project)

Ideally, I'd love to be able to say something like:
```
public class OpenApiController : ApiController
{
    private readonly IEnumerable<HttpConfiguration> _configurations;

    public OpenApiController(IEnumerable<HttpConfiguration> configurations)
    {
        _configurations = configurations.ToList();
    }

    [Route("swagger/v{apiVersion}")]
    public async Task<HttpResponseMessage> GetSwagger(uint apiVersion)
    {
        var settings = new WebApiToSwaggerGeneratorSettings
        {
....
        };

        var generator = new WebApiToSwaggerGenerator2(settings);
        var swagger = await generator.GenerateForControllersAsync(_configurations);

        return Request.CreateResponse(HttpStatusCode.OK, swagger);
    }
}
```

That being said, I am looking at transitioning my company's product to Core this year. I'm not nearly as familiar with the Core pipeline in comparison to OWIN.

**Comment by Cephei** [comment]
This is something I can look into though once I get further along with NSwag. Swashbuckle worked nicely out of the box and once I got going with it, however, I soon realized it's completely disconnected from JsonSchema. The Swashbuckle author also seems not interested in supporting polymorphism (which sucks in OpenAPI v2, but fully supported in the upcoming v3). The lack of inheritance and polymorphism support made me leave Swashbuckle entirely.

**Comment by rsuter** [comment]
I think we should remove the default entirely - a good compromise I think...

**Comment by Cephei** [comment]
Would it be reasonable to get this merged into CI today?

**Pull request merged**
