### PR TITLE
Added inline delegate-configuration for settings

### PR DESCRIPTION
**Pull request by weitzhandler**

### CODE REVIEW

**Comment by rsuter** [comment]
SwaggerJsonSchemaGenerator should not be exposed as public API and SwaggerUiOwinSettings inherits from JsonSchemaGeneratorSettings and thus you shouldn't create a second setting object of this type...

**Comment by weitzhandler** [comment]
@rsuter 
I followed the [original method](https://github.com/NSwag/NSwag/blob/master/src/NSwag.AspNetCore/SwaggerExtensions.cs#L70)'s pattern.

**Comment by rsuter** [comment]
Is my commit ok for you?

**Comment by weitzhandler** [comment]
Sure,
I'm pretty new to NSwag anyway, so if you feel that access to the schema settings is redundant than it's just great.
BTW, can you please help me with [my issue](../issues/553)?

**Pull request merged**
