### PR TITLE
Add date reviver to fetch (#62)

### PR DESCRIPTION
**Pull request by grovesNL**
Adds date reviver to fetch - uses the same methodology that was added to Angular

### CODE REVIEW

**Comment by rsuter** [comment]
The JSON reviver has been removed from the Angular 2 template because it is bad design when the user of the client class has to implement the correct JSON reviver (or may alter the behavior of the client class which is tailored to a specific service). We have to generate code that already works. 

My suggestion: Implement the reviver as is but remove it from the constructor and make the field protected. This way you can write an extension class and set the reviver in the extension class constructor. This way we ensure that the class behavior is encapsulated and everything is working right after the generation. 

What do you think?

Extension classes: https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#extended-classes-and-extension-code

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/pull/400

**Comment by grovesNL** [comment]
@rsuter: Agreed, that's a much better idea. I actually considered this when I added it but wanted to follow the Angular 2 template. Let's use the same pattern as #400 for fetch

**Comment by rsuter** [comment]
I've updated the wiki: https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#add-a-custom-jsonparse-reviver-function

**Comment by rsuter** [comment]
Just remove the ctor param and assignment and I'll merge both PRs...

**Comment by rsuter** [comment]
... and change the jsonParseReviver field to protected.

**Comment by grovesNL** [comment]
Thanks! I guess the only downside is that `jsonParseReviver` is a property instead of a method (like `transformOptions`) so it has to be set inside the constructor rather than a regular method override. I'm not sure if there is a way to declare it as a method instead.

**Comment by rsuter** [comment]
v6.21

**Comment by rsuter** [comment]
Using a method would be possible, but i think its fine as is...

**Comment by admir86** [comment]
Is that right, now I have to extend each service class if I need to set the `jsonParseReviver` for each generated class. Is there not a easier solution?
for me the solution with the optional constructor parameter was perfect, the user was able to change the `jsonParseReviver` but it was optional. 
but maybe I have not understand the problem with this solution

**Comment by RSuter** [comment]
In general I'd say that the user of the client should not be able to change the internal serialization logic as it should already be generated in a correct way otherwise it's a "leaky abstraction".

**Comment by admir86** [comment]
ok I understand. 
but it's also bad if I have to create for each new class an extend. the problem I have my nswag.json is on a share and I use it for all my projects to be sure the settings are always the same. If I have to extend the settings (`ExtensionClasses`), with each new api controller I have to create the nswag.json for each project.

Is there not a solution to resolve this problem with a base class? maybe call a function of the base class to set the `jsonParseReviver` ?

**Comment by RSuter** [comment]
Cant you set this in a common BaseClass?

**Comment by admir86** [comment]
yes, I can, It's just for the date deserialization. should be always the same.

**Pull request merged**
