### PR TITLE
Make model public

### PR DESCRIPTION
**Pull request by ShaKann**
Hi. From 5.x version I am able to use ITemplateFactory to provide my own templates. That's really good approach (I made something similar in my previous fork) but there is just one problem - models are still internal so I can't easily access theirs properties. Also I don't have intelisense on my T4 template. There will be much easier if I can use them directly in my code. I have create PR with appropriate changes. Please take a look and tell me: if this is good approach and if not how I can easily reuse your model?

### CODE REVIEW

**Comment by ShaKann** [comment]
Just one thing - I used stag comments as I don't know exactly what description will be correct.

**Comment by rsuter** [comment]
Yes, making the models public would be the next stop. Also some models are still dynamic (i.e. of type object) and must be converted to a strongly-typed class...

**Comment by ShaKann** [comment]
So, first you want to strongly-type model and then make it public? Ok... So when do you think this will be released and do you think I can help you with that?

**Comment by rsuter** [comment]
I will merge your PR, but we need to improve the XML comments first: 

- All tags on a single line
- Remove the <value> tags
- Add class <summary> tag contents (ie. "The CSharp client template model")

**Comment by rsuter** [comment]
Then we'll refactor the model classes and add typed model classes for the missing models (see Visual Studio Tasks)...

**Comment by rsuter** [comment]
For more discussions: https://github.com/NSwag/NSwag/issues/51

**Pull request merged**
