### PR TITLE
TypeScript response code handling bug

### PR DESCRIPTION
**Pull request by sandord**
Generating typescript client code for the controller below, resulted in exception throw statements for status codes that are not errors.

    public class FooController : ApiController
        {
            [Route("foos/")]
            [SwaggerResponse(200, null)]
            [SwaggerResponse(201, null)]
            [SwaggerResponse(400, null)]
            [SwaggerResponse(500, null)]
            public Foo[] GetFoos([FromUri] Bar[] bars)
            {
                return new Foo[0];
            }
        }

Before:

    protected processGetFoos(response: Response): void {
        const responseText = response.text();
        const status = response.status; 

        if (status === 200) {
            return null;
        } else if (status === 201) {
            this.throwException("A server error occurred.", status, responseText);
        } else if (status === 400) {
            this.throwException("A server error occurred.", status, responseText);
        } else if (status === 500) {
            this.throwException("A server error occurred.", status, responseText);
        } else if (status !== 200 && status !== 204) {
            this.throwException("An unexpected server error occurred.", status, responseText);
        }
        return null;
    }

Clearly, a HTTP 201 is not supposed to be handled as an error.

After:

    protected processGetFoos(response: Response): void {
        const responseText = response.text();
        const status = response.status; 

        if (status === 200) {
            return null;
        } else if (status === 201) {
            return null;
        } else if (status === 400) {
            this.throwException("A server error occurred.", status, responseText);
        } else if (status === 500) {
            this.throwException("A server error occurred.", status, responseText);
        } else if (status !== 200 && status !== 204) {
            this.throwException("An unexpected server error occurred.", status, responseText);
        }
        return null;
    }

### CODE REVIEW

**Comment by sandord** [comment]
The same bug is fixed in `CSharpOperationModel` as well, though I didn't include a test for that.

**Comment by rsuter** [comment]
This is not a bug but by design - what if 200 and 201 do not return the same response type? Then you would have not compilable code... Returning from 200 and 201 is only allowed if both have the same Response type...

**Comment by sandord** [comment]
I get it.

I actually wasn't returing both 200 and 201 in my case but due to the fact that I used the `[ResponseType(typeof(Model))]` attribute as well (that's the one from the `System.Web.Http.Description` namespace), a 200 was added in addition to my 201.

So it turns out that this:

        public class FooController : ApiController
        {
            [Route("foos/")]
            [System.Web.Http.Description.ResponseType(typeof(Foo[]))]
            [SwaggerResponse(201, null)]
            public IHttpActionResult GetFoos([FromUri] Bar[] bars)
            {
                return Ok(new Foo[0]);
            }
        }

leads to:

    protected processGetFoos(response: Response): Foo[] {
        const responseText = response.text();
        const status = response.status; 

        if (status === 200) {
            let result200: Foo[] = null;
            let resultData200 = responseText === "" ? null : JSON.parse(responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [];
                for (let item of resultData200)
                    result200.push(Foo.fromJS(item));
            }
            return result200;
        } else if (status === 201) {
            this.throwException("A server error occurred.", status, responseText);
        } else if (status !== 200 && status !== 204) {
            this.throwException("An unexpected server error occurred.", status, responseText);
        }
        return null;
    }

I guess I'll be removing all `[ResponseType(typeof(...))]` declarations in my code base where ever I have a `[SwaggerResponse(...)]` as well.

As a final thought, wouldn't it be great if I had been warned by the client generator that multiple non-error responses were declared? The client code generated in that case just doesn't make much sense anyhow. I'd say: either allow it and generate sensible code or prohibit it.

**Comment by grovesNL** [comment]
There was some discussion in #622 related to handling multiple non-exceptional response types

**Comment by grovesNL** [comment]
@sandord How did you end up handling this?

**Comment by sandord** [comment]
Since I wasn't really returning multiple success codes after all (a 200 snuck in due to the `ResponseModelAttribute`, next to my 201), I didn't have to.

**Pull request closed without merging**
