### PR TITLE
Enable binding a complex object array to webapi 2

### PR DESCRIPTION
**Pull request by aelbatal**
in relation with the following issue:
https://github.com/NSwag/NSwag/issues/492

### CODE REVIEW

**Comment by rsuter** [comment]
I you change this in this way, then for example string[] arrays are no longer supported, because it can only "serialize" complex objects... Your "special" foreach must only be applied for arrays of type object...

**Comment by ahmedelbatal** [comment]
I agree. how about now? I modified it to solve both simple and complex array types.

**Comment by rsuter** [comment]
The logic should be implemented in T4 and not in TypeScript because the array type is already available at generation time... Add a IsObjectArray (schema.Item.Type == JsonObjectType.Object) parameter to ParameterModel and use that...

**Comment by rsuter** [comment]
Thank you for the PR... how can we test this? do you generate the Swagger spec with NSwag?

**Comment by aelbatal** [comment]
Thank you for applying my edit. Unfortunately NSwag was hanging with some ApiControllers when I used it to generate the Swagger spec. I didn't spend much time to investigate this. So I'm now using the Swashbuckle Nuget Package to generate the Swagger spec, then passing it to `NSwag.SwaggerDocument.FromJsonAsync`.

**Comment by rsuter** [comment]
And this works with Swashbuckle? Can you provide a sample (web api action and swagger operation) so that we can support this scenario in nswag too?

**Pull request merged**
