### PR TITLE
Explicitly allow undefined as type of jsonParseReviver

### PR DESCRIPTION
**Pull request by grovesNL**
Added to Fetch/Angular templates

### CODE REVIEW

**Comment by grovesNL** [comment]
This is useful when using [`strictNullChecks`](https://www.typescriptlang.org/docs/release-notes/typescript-2.0.html)

**Comment by rsuter** [comment]
I think this breaks for all users of TS 1.8?

**Comment by grovesNL** [comment]
@rsuter You're right, I didn't realize `undefined` was only introduced as a type in 2.0. I'm not sure what to do without breaking 1.8 compatibility, unless I can opt in to 2.0+ functionality or diverge the templates. Currently the compiler will fail on that line for any project using `--strictNullChecks`, so anybody using it would have to post-process or create a separate template to modify that line (which I don't mind doing, but there may be others that hit the same issue).

**Comment by rsuter** [comment]
Added TypeScriptVersion setting: https://github.com/NJsonSchema/NJsonSchema/commit/7bfa8b3d5a609db70403310bc510434e7eac1828

**Comment by grovesNL** [comment]
@rsuter Great, thanks

**Comment by rsuter** [comment]
Feature added (see commit)

**Comment by rsuter** [comment]
v7.3

**Pull request closed without merging**
