### PR TITLE
Create response object webapi

### PR DESCRIPTION
**Pull request by Egorikas**
Web-api controller generator works in the same way like Client generator. I created a base class for CSharp templates and moved some properties to it. Also an unit-test for web-api wrapper was added.

### CODE REVIEW

**Comment by rsuter** [comment]
Thank you for the PR. Ill check this as soon as possible.

**Comment by rsuter** [comment]
Looks very good (see my comment). But you know that this will not yet work? If the response option is enabled, you need to transform the response into a web api http response in the generated web api controller...

**Comment by Egorikas** [comment]
Ok. I'll watch this when I have free time

**Comment by Egorikas** [comment]
@rsuter I'm sorry, I can't find your comment. Where is it? Thank you.

**Comment by rsuter** [comment]
I fixed the small issues, thank you. You can now test the version with the latest CI artifacts

**Comment by Egorikas** [comment]
Can you explain you phrase about 'you need to transform the response into a web api http response in the generated web api controller' (c)? I don't clearly understand it.

**Comment by rsuter** [comment]
With the newly added setting the following controller is generated: 

```
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "9.0.6248.18672")]
    [System.Web.Http.RoutePrefix("v2")]
    public partial class Controller : System.Web.Http.ApiController 
    {
        private IController _implementation; 
    
        public Controller(IController implementation)
        {
            _implementation = implementation; 
        }
        /// <summary>Add a new pet to the store</summary>
        /// <param name="body">Pet object that needs to be added to the store</param>
        [System.Web.Http.HttpPost, System.Web.Http.Route("pet")]
        public System.Threading.Tasks.Task<SwaggerResponse> AddPet(Pet body)
        {
            return _implementation.AddPetAsync(body);
        }
    
        /// <summary>Update an existing pet</summary>
        /// <param name="body">Pet object that needs to be added to the store</param>
        [System.Web.Http.HttpPut, System.Web.Http.Route("pet")]
        public System.Threading.Tasks.Task<SwaggerResponse> UpdatePet(Pet body)
        {
            return _implementation.UpdatePetAsync(body);
        }
    
        /// <summary>Finds Pets by status</summary>
        /// <param name="status">Status values that need to be considered for filter</param>
        /// <returns>successful operation</returns>
        [System.Web.Http.HttpGet, System.Web.Http.Route("pet/findByStatus")]
        public System.Threading.Tasks.Task<SwaggerResponse<System.Collections.Generic.List<Pet>>> FindPetsByStatus(System.Collections.Generic.IEnumerable<Anonymous> status)
        {
            return _implementation.FindPetsByStatusAsync(status);
        }
```

But this will not work, because Web API does not know how to treat `SwaggerResponse<System.Collections.Generic.List<Pet>>`.

If WrapSuccessResponses is enabled, then the controller code should look like 

```
[System.Web.Http.HttpGet, System.Web.Http.Route("pet/findByStatus")]
public System.Threading.Tasks.Task<SwaggerResponse<System.Collections.Generic.List<Pet>>> FindPetsByStatus(System.Collections.Generic.IEnumerable<Anonymous> status)
{
	var result = await _implementation.FindPetsByStatusAsync(status);

	HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK, result.Result);
	
	foreach (var header in result.Headers)
		response.Headers[header.Key] = header.Value;
	
	return response;
}
```

**Comment by Egorikas** [comment]
Ok. Thank you. I'll try to implement this later)

**Pull request merged**
