### PR TITLE
Specify text/binary types explicitly

### PR DESCRIPTION
**Pull request by grovesNL**
As mentioned in my #613 comment, currently it's difficult to submit pull requests and perform diffs because the line endings are configured in each user's git settings. `text=auto` should automatically handle this for the issue raised in #613 and each user's git settings do not have to match.

### CODE REVIEW

**Comment by rsuter** [comment]
Sorry, the main reason of this was that .tt files need CRLF: https://github.com/NSwag/NSwag/commit/49981ab475ae60948f6ed25b6bb8f4a22c421317

**Comment by rsuter** [comment]
Should I use your .gitattributes? Or is it fine as it is now?

**Comment by grovesNL** [comment]
@rsuter No problem! I'll try again tomorrow to check.

Although it's probably a good idea to specify `text=auto` and the other types explicitly anyway, in case other developers have different git settings or are using the Linux/OS X defaults. You can merge my .gitattributes if you think it's useful.

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/560b1751abe1e50540912c92de605c6b26caee7b

**Comment by grovesNL** [comment]
Perfect thanks!

**Pull request closed without merging**
