### PR TITLE
Addition of UseHttpRequestMessageCreationMethod option

### PR DESCRIPTION
**Pull request by aarro**
I needed the ability to modify headers, namely the Authorization header, on each request before it was sent. In order to do that and still stay in the spirit of supporting the UseHttpClientCreationMethod option, where it felt really hacky to attempt to use the HttpClient's DefaultRequestHeaders, I created a new option for UseHttpRequestMessageCreationMethod. This allows the base class to handle the creation of an HttpRequestMessage object that's used by all calls.

In order to support using the HttpRequestMessage for all calls, I also changed all the verb-based methods being used off of HttpClient to be SendAsync.

### CODE REVIEW

**Comment by rsuter** [comment]
You should make this method async so that it can be used in more scenarios: 

    await CreateHttpRequestMessageAsync(cancellationToken).ConfigureAwait(false);

**Comment by aarro** [comment]
Good idea...done.

**Comment by rsuter** [comment]
Ok merged, please check if everything is fine with the latest code in the "master" branch...

**Comment by rsuter** [comment]
Added setting to UI: https://github.com/NSwag/NSwag/commit/305db1d4afcd4179fec2b0ea70127af631cfe4b5

**Comment by rsuter** [comment]
Thanks for the PR

**Comment by rsuter** [comment]
With this change, we can also remove 
    internal static class HttpExtensions
correct?

**Comment by aarro** [comment]
Yes I think HttpExtensions can go away...sorry I didn't notice that before.

**Comment by rsuter** [comment]
Ok, removed: https://github.com/NSwag/NSwag/commit/0ec3f6b01d37f2b1777c414383a8166c783cf5b1

Thanks for your contribution.

**Pull request merged**
